# Generated by Django 6.1.1 on 2026-09-24 20:52

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("secrets", encrypted_fields.fields.EncryptedJSONField(default=dict)),
                ("guest_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_identity",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[],
            options={
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.identitymodel",),
        ),
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="core.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "core_tag",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name", "entity"),
                        name="unique_tag_per_owner_and_entity",
                    )
                ],
            },
        ),
    ]
