# Generated by Django 6.1.1 on 2026-09-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identitymodel",
            name="auth_user",
        ),
        migrations.RemoveField(
            model_name="identitymodel",
            name="guest_id",
        ),
    ]
