# Generated by Django 6.1.1 on 2026-09-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_identity_by_name_alone"),
        ("history", "0001_initial"),
        ("repo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerStateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "worker_state",
            },
        ),
        migrations.CreateModel(
            name="ControlsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paused", models.BooleanField(default=False)),
                ("stopping", models.PositiveSmallIntegerField(default=0)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "worker_controls",
            },
        ),
        migrations.CreateModel(
            name="JobModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=16),
                ),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("queued", models.DateTimeField(blank=True, default=None, null=True)),
                ("tokens", models.PositiveIntegerField(default=0)),
                ("counted", models.BooleanField(default=False)),
                ("started", models.DateTimeField(blank=True, default=None, null=True)),
                ("beat", models.DateTimeField(blank=True, default=None, null=True)),
                ("finished", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "coercion_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.coercionbranchmodel",
                    ),
                ),
                (
                    "configuration_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.configurationbranchmodel",
                    ),
                ),
                (
                    "instruction_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.instructionbranchmodel",
                    ),
                ),
                (
                    "output_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.outputbranchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.identitymodel",
                    ),
                ),
                (
                    "reasoning_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.reasoningbranchmodel",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="history.runmodel",
                    ),
                ),
                (
                    "sampling_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.samplingbranchmodel",
                    ),
                ),
                (
                    "stack_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.stackbranchmodel",
                    ),
                ),
                (
                    "toolset_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.toolsetbranchmodel",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="history.trialmodel",
                    ),
                ),
            ],
            options={
                "db_table": "worker_job",
                "ordering": ("pk",),
            },
        ),
    ]
