# Generated by Django 6.1.1 on 2026-09-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_pgqueuer_schema"),
        ("history", "0001_initial"),
        ("repo", "0003_output_answer_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerStateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paused", models.BooleanField(default=False)),
                ("stopping", models.PositiveSmallIntegerField(default=0)),
                ("seen", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "worker_state",
            },
        ),
        migrations.CreateModel(
            name="QueuedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch",
                    models.UUIDField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                ("drain", models.PositiveIntegerField(db_index=True)),
                ("queued", models.DateTimeField(auto_now_add=True)),
                ("configuration", models.CharField(max_length=255)),
                ("stack", models.CharField(max_length=255)),
                ("set", models.JSONField(blank=True, default=dict)),
                ("label", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=128)),
                ("case", models.CharField(max_length=255)),
                ("seed", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=16),
                ),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                ("tokens", models.PositiveIntegerField(default=0)),
                ("counted", models.BooleanField(default=False)),
                ("started", models.DateTimeField(blank=True, default=None, null=True)),
                ("beat", models.DateTimeField(blank=True, default=None, null=True)),
                ("finished", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "case_trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="repo.casetrailmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.identitymodel",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="history.runmodel",
                    ),
                ),
            ],
            options={
                "db_table": "worker_queued",
                "ordering": ("pk",),
            },
        ),
    ]
