# Generated by Django 6.1.1 on 2026-09-26 12:10

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_pgqueuer_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("configuration", models.CharField(max_length=255)),
                ("stack", models.CharField(max_length=255)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255)
                    ),
                ),
                ("variations", models.JSONField(default=dict)),
                ("seed", models.BigIntegerField(blank=True, default=None, null=True)),
                ("cells", models.JSONField(default=list)),
                ("held_back", models.JSONField(default=list)),
                ("cases", models.JSONField(default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "portal_batch",
                "ordering": ("-timestamp", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("portal.batchmodel",),
        ),
    ]
