# Generated by Django 6.1.1 on 2026-09-27 19:26

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('history', '0001_initial'),
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('repo.casebranchmodel',),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('repo.configurationbranchmodel',),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('history.runmodel',),
        ),
        migrations.CreateModel(
            name='Sampling',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('repo.samplingbranchmodel',),
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('repo.stackbranchmodel',),
        ),
        migrations.CreateModel(
            name='BatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.CharField(max_length=255)),
                ('stack', models.CharField(max_length=255)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255))),
                ('variations', models.JSONField(default=dict)),
                ('seed', models.BigIntegerField(blank=True, default=None, null=True)),
                ('cells', models.JSONField(default=list)),
                ('held_back', models.JSONField(default=list)),
                ('cases', models.JSONField(default=list)),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.identitymodel')),
            ],
            options={
                'db_table': 'portal_batch',
                'ordering': ('-timestamp', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.batchmodel',),
        ),
    ]
