# Generated by Django 6.1.1 on 2026-09-26 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
        ("repo", "0004_case_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("repo.casebranchmodel",),
        ),
    ]
