# Generated by Django 6.1.1 on 2026-09-26 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
        ("portal", "0002_case"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("history.runmodel",),
        ),
    ]
