# Generated by Django 6.1.1 on 2026-09-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_run"),
        ("repo", "0004_case_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stack",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("repo.stackbranchmodel",),
        ),
    ]
