# Generated by Django 6.1.1 on 2026-09-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_stack"),
        ("repo", "0004_case_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("repo.configurationbranchmodel",),
        ),
    ]
