# Generated by Django 6.1.1 on 2026-09-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_configuration"),
        ("repo", "0004_case_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sampling",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("repo.samplingbranchmodel",),
        ),
    ]
