# Generated by Django 6.0.5 on 2026-05-19 12:30

import uuid

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models

import chatddx.core.decimals
import chatddx.core.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("ollama", "Ollama"),
                            ("vllm", "vLLM"),
                        ],
                        max_length=255,
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("endpoint", models.URLField(max_length=2048)),
                ("profile", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "agents_connection",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputTypeTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "definition",
                    chatddx.core.django_fields.JSONSchemaField(default=dict),
                ),
                (
                    "validation_strategy",
                    models.CharField(
                        choices=[
                            ("noop", "Noop"),
                            ("retry", "Retry"),
                            ("inform", "Inform"),
                            ("crash", "Crash"),
                        ],
                        default="inform",
                        max_length=255,
                    ),
                ),
                (
                    "coercion_strategy",
                    models.CharField(
                        choices=[
                            ("prompted", "Prompted"),
                            ("tool", "Tool"),
                            ("native", "Native"),
                        ],
                        default="native",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "agents_output_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SamplingParamsTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "top_p",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("seed", models.IntegerField(blank=True, default=None, null=True)),
                ("n", models.PositiveIntegerField(blank=True, default=None, null=True)),
                (
                    "presence_penalty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "frequency_penalty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "logit_bias",
                    models.JSONField(
                        blank=True,
                        decoder=chatddx.core.decimals.DecimalDecoder,
                        default=dict,
                        encoder=chatddx.core.decimals.DecimalEncoder,
                    ),
                ),
                ("provider_params", models.JSONField(blank=True, default=dict)),
                (
                    "stop_sequences",
                    models.JSONField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "db_table": "agents_sampling_params",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolGroupTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("instructions", models.TextField()),
                (
                    "tools",
                    chatddx.core.django_fields.RelatedArrayField(
                        associated_model=chatddx.repo.entities.tool.django.ToolTrailModel,
                        base_field=models.IntegerField(),
                        default=list,
                    ),
                ),
            ],
            options={
                "db_table": "agents_tool_group",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "command",
                    models.CharField(
                        db_index=True, help_text="Name of the tool", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("function", "Function"),
                            ("code_interpreter", "Code Interpreter"),
                            ("file_search", "File Search"),
                            ("web_search", "Web Search"),
                        ],
                        default="function",
                        help_text="The type of tool.",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("parameters", chatddx.core.django_fields.JSONSchemaField()),
            ],
            options={
                "db_table": "agents_tool",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("instructions", models.TextField()),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.connectiontrailmodel",
                    ),
                ),
                (
                    "output_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.outputtypetrailmodel",
                    ),
                ),
                (
                    "sampling_params",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.samplingparamstrailmodel",
                    ),
                ),
                (
                    "tool_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.toolgrouptrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdentityModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("secrets", encrypted_fields.fields.EncryptedJSONField(default=dict)),
                ("guest_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_identity",
            },
        ),
        migrations.CreateModel(
            name="AgentBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.agenttrailmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_branch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputTypeBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.outputtypetrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_output_type_branch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SamplingParamsBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.samplingparamstrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_sampling_params_branch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "default_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.agentbranchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_session",
            },
        ),
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("request", "Request"), ("response", "Response")],
                        max_length=255,
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.agenttrailmodel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="orm.sessionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_message",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ToolGroupBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.toolgrouptrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_tool_group_branch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.tooltrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_tool_branch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectionBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.connectiontrailmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_connection_branch",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "name", "-timestamp"],
                        name="agents_conn_owner_i_3a81d6_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agentbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_agen_owner_i_c9688a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outputtypebranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_outp_owner_i_8e4c40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="samplingparamsbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_samp_owner_i_1f8b1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolgroupbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_tool_owner_i_384545_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_tool_owner_i_e1f0a7_idx",
            ),
        ),
    ]
