# Generated by Django 6.1.1 on 2026-09-24 20:46

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models

import chatddx.core.django_fields
import chatddx.django.orm.utils
import chatddx.repo.entities.tool.django
import chatddx.repo.families.django


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("vignette", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("build", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoercionBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoercionTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("mode", models.CharField(max_length=16)),
                ("schema_prompt", models.TextField(blank=True, null=True)),
                ("tool_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConfigurationBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstructionTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("system", models.TextField(blank=True)),
                ("user", models.TextField()),
                ("variables", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LLMTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("snapshot", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MachineTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("machine_id", models.UUIDField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OsTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("toplevel", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "json_schema",
                    chatddx.repo.families.django.OrderedJSONField(
                        blank=True, null=True
                    ),
                ),
                ("guidance", models.TextField(blank=True, null=True)),
                ("views", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReasoningTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("effort", models.CharField(max_length=16)),
                ("budget", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SamplingTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("defaults", models.CharField(max_length=32)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("top_p", models.FloatField(blank=True, null=True)),
                ("top_k", models.IntegerField(blank=True, null=True)),
                ("max_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("presence_penalty", models.FloatField(blank=True, null=True)),
                ("frequency_penalty", models.FloatField(blank=True, null=True)),
                ("stop", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScorerTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("function", models.CharField(max_length=255)),
                ("view", models.CharField(max_length=32)),
                ("target_kind", models.CharField(blank=True, max_length=32, null=True)),
                ("args", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServingTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("engine", models.TextField()),
                ("args", models.JSONField(blank=True, default=dict)),
                ("env", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolsetTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("guidance", models.TextField(blank=True, null=True)),
                (
                    "tools",
                    chatddx.core.django_fields.RelatedArrayField(
                        associated_model=chatddx.repo.entities.tool.django.ToolTrailModel,
                        base_field=models.IntegerField(),
                        default=list,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("parameters", chatddx.repo.families.django.OrderedJSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                "orm.casebranchmodel",
                models.Model,
                chatddx.django.orm.utils.Sharable,
            ),
        ),
        migrations.CreateModel(
            name="SharedCase",
            fields=[],
            options={
                "verbose_name": "Shared Case",
                "verbose_name_plural": "Shared Cases",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                "orm.casebranchmodel",
                models.Model,
                chatddx.django.orm.utils.Sharable,
            ),
        ),
        migrations.AddField(
            model_name="casebranchmodel",
            name="trail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="orm.casetrailmodel",
            ),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.clientbranchmodel", models.Model),
        ),
        migrations.AddField(
            model_name="clientbranchmodel",
            name="trail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="orm.clienttrailmodel",
            ),
        ),
        migrations.CreateModel(
            name="Coercion",
            fields=[],
            options={
                "verbose_name": "Coercion",
                "verbose_name_plural": "Coercions",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.coercionbranchmodel", models.Model),
        ),
        migrations.AddField(
            model_name="coercionbranchmodel",
            name="trail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="orm.coerciontrailmodel",
            ),
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                "orm.configurationbranchmodel",
                models.Model,
                chatddx.django.orm.utils.Sharable,
            ),
        ),
        migrations.CreateModel(
            name="SharedConfiguration",
            fields=[],
            options={
                "verbose_name": "Shared Configuration",
                "verbose_name_plural": "Shared Configurations",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                "orm.configurationbranchmodel",
                models.Model,
                chatddx.django.orm.utils.Sharable,
            ),
        ),
        migrations.CreateModel(
            name="ConfigurationTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "coercion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="orm.coerciontrailmodel",
                    ),
                ),
                (
                    "instruction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="orm.instructiontrailmodel",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="orm.outputtrailmodel",
                    ),
                ),
                (
                    "reasoning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="orm.reasoningtrailmodel",
                    ),
                ),
                (
                    "sampling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="orm.samplingtrailmodel",
                    ),
                ),
                (
                    "toolset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="orm.toolsettrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="configurationbranchmodel",
            name="trail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="orm.configurationtrailmodel",
            ),
        ),
        migrations.CreateModel(
            name="IdentityModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("secrets", encrypted_fields.fields.EncryptedJSONField(default=dict)),
                ("guest_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ConversationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("context", models.CharField(max_length=16)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_conversations",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="configurationbranchmodel",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="shared_%(class)s", to="orm.identitymodel"
            ),
        ),
        migrations.AddField(
            model_name="configurationbranchmodel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_%(class)s",
                to="orm.identitymodel",
            ),
        ),
        migrations.AddField(
            model_name="coercionbranchmodel",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="shared_%(class)s", to="orm.identitymodel"
            ),
        ),
        migrations.AddField(
            model_name="coercionbranchmodel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_%(class)s",
                to="orm.identitymodel",
            ),
        ),
        migrations.AddField(
            model_name="clientbranchmodel",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="shared_%(class)s", to="orm.identitymodel"
            ),
        ),
        migrations.AddField(
            model_name="clientbranchmodel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_%(class)s",
                to="orm.identitymodel",
            ),
        ),
        migrations.AddField(
            model_name="casebranchmodel",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="shared_%(class)s", to="orm.identitymodel"
            ),
        ),
        migrations.AddField(
            model_name="casebranchmodel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_%(class)s",
                to="orm.identitymodel",
            ),
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[],
            options={
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.identitymodel",),
        ),
        migrations.CreateModel(
            name="InstructionBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.instructiontrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[],
            options={
                "verbose_name": "Instruction",
                "verbose_name_plural": "Instructions",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.instructionbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="LLMBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.llmtrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LLM",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.llmbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="MachineBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.machinetrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.machinebranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_uuid", models.UUIDField(db_index=True)),
                ("role", models.CharField(max_length=16)),
                ("kind", models.CharField(max_length=16)),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="orm.conversationmodel",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="OsBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.ostrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Os",
            fields=[],
            options={
                "verbose_name": "OS",
                "verbose_name_plural": "OSes",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.osbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="OutputBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.outputtrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Output",
            fields=[],
            options={
                "verbose_name": "Output",
                "verbose_name_plural": "Outputs",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.outputbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="ReasoningBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.reasoningtrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reasoning",
            fields=[],
            options={
                "verbose_name": "Reasoning",
                "verbose_name_plural": "Reasoning",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.reasoningbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="RunModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=16)),
                (
                    "client_rev",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("client_packages", models.JSONField(blank=True, default=dict)),
                ("started", models.DateTimeField(blank=True, default=None, null=True)),
                ("finished", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "requests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "responses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "answer",
                    chatddx.repo.families.django.OrderedJSONField(
                        blank=True, default=None, null=True
                    ),
                ),
                ("valid", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "finish_reason",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("error", models.TextField(blank=True, default=None, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="orm.clienttrailmodel",
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True, related_name="shared_runs", to="orm.identitymodel"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="orm.conversationmodel",
                    ),
                ),
                (
                    "llm_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="orm.llmbranchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SamplingBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.samplingtrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sampling",
            fields=[],
            options={
                "verbose_name": "Sampling",
                "verbose_name_plural": "Sampling",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.samplingbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="ScorerBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.scorertrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Scorer",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.scorerbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="ScoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scorer_name", models.CharField(max_length=255)),
                ("target", models.TextField(blank=True, default=None, null=True)),
                ("blob", models.CharField(max_length=64)),
                ("value", models.FloatField(blank=True, default=None, null=True)),
                ("answer", models.TextField(blank=True, default=None, null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "case_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="orm.casebranchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="orm.runmodel",
                    ),
                ),
                (
                    "scorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="orm.scorertrailmodel",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="ServingBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.servingtrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Serving",
            fields=[],
            options={
                "verbose_name": "Serving",
                "verbose_name_plural": "Servings",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.servingbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="StackBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="runmodel",
            name="stack_branch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="orm.stackbranchmodel",
            ),
        ),
        migrations.CreateModel(
            name="Stack",
            fields=[],
            options={
                "verbose_name": "Stack",
                "verbose_name_plural": "Stacks",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.stackbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="StackTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=128, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "host_os",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosted_stacks",
                        to="orm.ostrailmodel",
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stacks",
                        to="orm.llmtrailmodel",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stacks",
                        to="orm.machinetrailmodel",
                    ),
                ),
                (
                    "os",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stacks",
                        to="orm.ostrailmodel",
                    ),
                ),
                (
                    "serving",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stacks",
                        to="orm.servingtrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="stackbranchmodel",
            name="trail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="orm.stacktrailmodel",
            ),
        ),
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="orm.identitymodel",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="stackbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="servingbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="scorerbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="samplingbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="reasoningbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="outputbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="osbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="machinebranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="llmbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="instructionbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="configurationbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="coercionbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="clientbranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.AddField(
            model_name="casebranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
            ),
        ),
        migrations.CreateModel(
            name="ToolBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.tooltrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RunToolBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blob", models.CharField(max_length=64)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orm.runmodel"
                    ),
                ),
                (
                    "tool_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.toolbranchmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runmodel",
            name="tool_branches",
            field=models.ManyToManyField(
                blank=True,
                related_name="runs",
                through="orm.RunToolBranchModel",
                to="orm.toolbranchmodel",
            ),
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.toolbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="ToolsetBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tagged_%(class)s", to="orm.tagmodel"
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.toolsettrailmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Toolset",
            fields=[],
            options={
                "verbose_name": "Toolset",
                "verbose_name_plural": "Toolsets",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.toolsetbranchmodel", models.Model),
        ),
        migrations.CreateModel(
            name="TrialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("seed", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="orm.casetrailmodel",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="orm.configurationtrailmodel",
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="orm.stacktrailmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runmodel",
            name="trial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="orm.trialmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagmodel",
            constraint=models.UniqueConstraint(
                fields=("owner", "name", "entity"),
                name="unique_tag_per_owner_and_entity",
            ),
        ),
        migrations.AddIndex(
            model_name="stackbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_stackbr_owner_i_66f910_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servingbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_serving_owner_i_cdb239_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scorerbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_scorerb_owner_i_e34365_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="samplingbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_samplin_owner_i_28db28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reasoningbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_reasoni_owner_i_ccb0d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outputbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_outputb_owner_i_26c4ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="osbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_osbranc_owner_i_87a9ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="machinebranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_machine_owner_i_c1b343_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_llmbran_owner_i_9e379e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instructionbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_instruc_owner_i_38ba87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="configurationbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_configu_owner_i_968ce1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coercionbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_coercio_owner_i_14a75a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clientbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_clientb_owner_i_77b428_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casebranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_casebra_owner_i_3fb15d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolsetbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_toolset_owner_i_f2a3ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolbranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="orm_toolbra_owner_i_aa5575_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="trialmodel",
            constraint=models.UniqueConstraint(
                fields=("configuration", "stack", "case", "seed"),
                name="one_trial_per_cell_case_and_seed",
                nulls_distinct=False,
            ),
        ),
    ]
