# Generated by Django 6.0.5 on 2026-05-21 18:11

from django.db import migrations

import chatddx.repo.families.django


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(chatddx.repo.families.django.BranchProxy, "orm.agentbranchmodel"),
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx.repo.families.django.BranchProxy,
                "orm.connectionbranchmodel",
            ),
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[],
            options={
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.identitymodel",),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.messagemodel",),
        ),
        migrations.CreateModel(
            name="OutputType",
            fields=[],
            options={
                "verbose_name": "Output type",
                "verbose_name_plural": "Output types",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx.repo.families.django.BranchProxy,
                "orm.outputtypebranchmodel",
            ),
        ),
        migrations.CreateModel(
            name="SamplingParams",
            fields=[],
            options={
                "verbose_name": "Sampling parameters",
                "verbose_name_plural": "Sampling parameters",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx.repo.families.django.BranchProxy,
                "orm.samplingparamsbranchmodel",
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.sessionmodel",),
        ),
        migrations.CreateModel(
            name="SuperAgent",
            fields=[],
            options={
                "verbose_name": "Super Agent",
                "verbose_name_plural": "Super Agents",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(chatddx.repo.families.django.BranchProxy, "orm.agentbranchmodel"),
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(chatddx.repo.families.django.BranchProxy, "orm.toolbranchmodel"),
        ),
        migrations.CreateModel(
            name="ToolGroup",
            fields=[],
            options={
                "verbose_name": "Tool group",
                "verbose_name_plural": "Tool groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx.repo.families.django.BranchProxy,
                "orm.toolgroupbranchmodel",
            ),
        ),
    ]
