# Generated by Django 6.1.1 on 2026-09-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0002_pgqueuer_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="runmodel",
            name="client",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="orm.clienttrailmodel",
            ),
        ),
        migrations.AddField(
            model_name="runmodel",
            name="client_packages",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="runmodel",
            name="client_rev",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
