# Generated by Django 6.0.5 on 2026-07-22 16:29

from django.db import migrations

import chatddx.django.orm.utils
import chatddx.repo.families.django


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0008_agentbranchmodel_collaborators_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedAgent",
            fields=[],
            options={
                "verbose_name": "Shared Agent (simple)",
                "verbose_name_plural": "Shared Agents (simple)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx.repo.families.django.BranchProxy,
                "orm.agentbranchmodel",
                chatddx.django.orm.utils.Sharable,
            ),
        ),
        migrations.CreateModel(
            name="SharedSuperAgent",
            fields=[],
            options={
                "verbose_name": "Shared Agent",
                "verbose_name_plural": "Shared Agents",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx.repo.families.django.BranchProxy,
                "orm.agentbranchmodel",
                chatddx.django.orm.utils.Sharable,
            ),
        ),
    ]
