# Generated by Django 6.0.5 on 2026-09-08 17:44

import chatddx.repo.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0009_sharedagent_sharedsuperagent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("payload", models.TextField()),
            ],
            options={
                "db_table": "agents_case",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.casetrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_case_branch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(chatddx.repo.base.BranchProxy, "orm.casebranchmodel"),
        ),
        migrations.AddIndex(
            model_name="casebranchmodel",
            index=models.Index(
                fields=["owner", "name", "-timestamp"],
                name="agents_case_owner_i_eae70e_idx",
            ),
        ),
    ]
