# Generated by Django 6.0.5 on 2026-09-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0010_casetrailmodel_casebranchmodel_case_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpectTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("payload", models.TextField()),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expects",
                        to="orm.casetrailmodel",
                    ),
                ),
                (
                    "output_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expects",
                        to="orm.outputtypetrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_expect",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpectBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.expecttrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_expect_branch",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "name", "-timestamp"],
                        name="agents_expe_owner_i_dbd636_idx",
                    )
                ],
            },
        ),
    ]
