# Generated by Django 6.1.1 on 2026-09-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0010_pgqueuer_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="coerciontrailmodel",
            name="tool_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
