# Generated by Django 6.1.1 on 2026-09-19 15:56

import uuid

import django.db.models.deletion
from django.db import migrations, models

import chatddx.django.orm.utils
import chatddx.repo.families.django


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_pgqueuer_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.TextField()),
            ],
            options={
                'db_table': 'agents_case',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpectTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.TextField()),
            ],
            options={
                'db_table': 'agents_expect',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScorerTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'agents_scorer',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='context',
            field=models.CharField(choices=[('chat', 'Chat'), ('repl', 'REPL'), ('experiment', 'Experiment')], default='chat', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='connectionbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='outputtypebranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='samplingparamsbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='toolbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='toolgroupbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='tooltrailmodel',
            name='command',
            field=models.CharField(db_index=True, help_text='Command the tool invoces', max_length=255),
        ),
        migrations.CreateModel(
            name='CaseBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='orm.casetrailmodel')),
            ],
            options={
                'db_table': 'agents_case_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(chatddx.repo.families.django.BranchProxy, 'orm.casebranchmodel', chatddx.django.orm.utils.Sharable),
        ),
        migrations.CreateModel(
            name='SharedCase',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Case',
                'verbose_name_plural': 'Shared Cases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(chatddx.repo.families.django.BranchProxy, 'orm.casebranchmodel', chatddx.django.orm.utils.Sharable),
        ),
        migrations.CreateModel(
            name='ExpectBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='orm.expecttrailmodel')),
            ],
            options={
                'db_table': 'agents_expect_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expect',
            fields=[
            ],
            options={
                'verbose_name': 'Expect',
                'verbose_name_plural': 'Expects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(chatddx.repo.families.django.BranchProxy, 'orm.expectbranchmodel', chatddx.django.orm.utils.Sharable),
        ),
        migrations.CreateModel(
            name='CaseExpect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.casebranchmodel')),
                ('expect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.expecttrailmodel')),
            ],
            options={
                'db_table': 'agents_case_expect_link',
            },
        ),
        migrations.AddField(
            model_name='casebranchmodel',
            name='expects',
            field=models.ManyToManyField(related_name='cases', through='orm.CaseExpect', through_fields=('case', 'expect'), to='orm.expecttrailmodel'),
        ),
        migrations.CreateModel(
            name='ExperimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='orm.agenttrailmodel')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='orm.casetrailmodel')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_experiments', to='orm.identitymodel')),
                ('expect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='orm.expecttrailmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orm.identitymodel')),
            ],
            options={
                'db_table': 'agents_experiment',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
            ],
            options={
                'verbose_name': 'Experiment',
                'verbose_name_plural': 'Experiments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orm.experimentmodel',),
        ),
        migrations.CreateModel(
            name='RunModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('queued', 'Queued'), ('running', 'Running'), ('errored', 'Errored'), ('completed', 'Completed'), ('scored', 'Scored')], default='stored', max_length=255)),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_runs', to='orm.identitymodel')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='orm.experimentmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orm.identitymodel')),
                ('session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='orm.sessionmodel')),
            ],
            options={
                'db_table': 'agents_run',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
            ],
            options={
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orm.runmodel',),
        ),
        migrations.CreateModel(
            name='ScorerBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='orm.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='orm.scorertrailmodel')),
            ],
            options={
                'db_table': 'agents_scorer_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scorer',
            fields=[
            ],
            options={
                'verbose_name': 'Scorer',
                'verbose_name_plural': 'Scorers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(chatddx.repo.families.django.BranchProxy, 'orm.scorerbranchmodel', chatddx.django.orm.utils.Sharable),
        ),
        migrations.CreateModel(
            name='SharedScorer',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Scorer',
                'verbose_name_plural': 'Shared Scorers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(chatddx.repo.families.django.BranchProxy, 'orm.scorerbranchmodel', chatddx.django.orm.utils.Sharable),
        ),
        migrations.AddField(
            model_name='expecttrailmodel',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expects', to='orm.scorertrailmodel'),
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='orm.identitymodel')),
            ],
            options={
                'db_table': 'agents_tag',
            },
        ),
        migrations.AddField(
            model_name='scorerbranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.AddField(
            model_name='expectbranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.AddField(
            model_name='casebranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.AddField(
            model_name='agentbranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.AddField(
            model_name='connectionbranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.AddField(
            model_name='outputtypebranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.AddField(
            model_name='samplingparamsbranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.AddField(
            model_name='toolbranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.AddField(
            model_name='toolgroupbranchmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='orm.tagmodel'),
        ),
        migrations.CreateModel(
            name='SharedExperiment',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Experiment',
                'verbose_name_plural': 'Shared Experiments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orm.experiment',),
        ),
        migrations.CreateModel(
            name='SharedRun',
            fields=[
            ],
            options={
                'verbose_name': 'Shared Run',
                'verbose_name_plural': 'Shared Runs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orm.run',),
        ),
        migrations.AddConstraint(
            model_name='tagmodel',
            constraint=models.UniqueConstraint(fields=('owner', 'name', 'entity'), name='unique_tag_per_owner_and_entity'),
        ),
        migrations.AddIndex(
            model_name='scorerbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='agents_scor_owner_i_930e23_idx'),
        ),
        migrations.AddIndex(
            model_name='expectbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='agents_expe_owner_i_dbd636_idx'),
        ),
        migrations.AddIndex(
            model_name='casebranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='agents_case_owner_i_eae70e_idx'),
        ),
    ]
