# Generated by Django 6.1.1 on 2026-09-24 07:37

import chatddx.repo.families.django
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0011_coercion_tool_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="stored", max_length=16)),
                ("started", models.DateTimeField(blank=True, default=None, null=True)),
                ("finished", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "requests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "responses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "output",
                    chatddx.repo.families.django.OrderedJSONField(
                        blank=True, default=None, null=True
                    ),
                ),
                ("valid", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "finish_reason",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("error", models.TextField(blank=True, default=None, null=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True, related_name="shared_runs", to="orm.identitymodel"
                    ),
                ),
                (
                    "model_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="orm.modelbranchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "stack_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="orm.stackbranchmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunToolBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orm.runmodel"
                    ),
                ),
                (
                    "tool_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.toolbranchmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runmodel",
            name="tool_branches",
            field=models.ManyToManyField(
                blank=True,
                related_name="runs",
                through="orm.RunToolBranchModel",
                to="orm.toolbranchmodel",
            ),
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("context", models.CharField(max_length=16)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_sessions",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runmodel",
            name="session",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="orm.sessionmodel",
            ),
        ),
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("role", models.CharField(max_length=16)),
                ("kind", models.CharField(max_length=16)),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="orm.sessionmodel",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="TrialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("seed", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="orm.casetrailmodel",
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True, related_name="shared_trials", to="orm.identitymodel"
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="orm.configurationtrailmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="orm.stacktrailmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runmodel",
            name="trial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="orm.trialmodel",
            ),
        ),
    ]
