# Generated by Django 6.0.5 on 2026-09-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0011_expecttrailmodel_expectbranchmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "agents_tag",
            },
        ),
        migrations.AddField(
            model_name="casebranchmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="case_branches", to="orm.tagmodel"
            ),
        ),
    ]
