# Generated by Django 6.1.1 on 2026-09-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0011_casetrailmodel_expecttrailmodel_scorertrailmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetrailmodel',
            name='expects',
        ),
        migrations.AlterField(
            model_name='agentbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='casebranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='connectionbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='expectbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='outputtypebranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='samplingparamsbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='scorerbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='toolbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.AlterField(
            model_name='toolgroupbranchmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='orm.identitymodel'),
        ),
        migrations.CreateModel(
            name='CaseExpect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.casetrailmodel')),
                ('expect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.expecttrailmodel')),
            ],
            options={
                'db_table': 'agents_case_expect_link',
            },
        ),
    ]
