# Generated by Django 6.1.1 on 2026-09-20 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0012_case_expects_name_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="orm.agenttrailmodel",
                    ),
                ),
                (
                    "case_tags",
                    models.ManyToManyField(related_name="batches", to="orm.tagmodel"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "scorers",
                    models.ManyToManyField(
                        blank=True, related_name="batches", to="orm.scorerbranchmodel"
                    ),
                ),
            ],
            options={
                "db_table": "agents_batch",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.batchmodel",),
        ),
        migrations.AddField(
            model_name="experimentmodel",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="experiments",
                to="orm.batchmodel",
            ),
        ),
    ]
