# Generated by Django 6.0.5 on 2026-09-08 22:36

import django.db.models.deletion
from django.db import migrations, models


def split_tags_by_owner(apps, schema_editor):
    """Backfill TagModel.owner, splitting any tag shared across owners.

    Tags predate owner-scoping and were looked up by name alone, so the
    same row could be (and, via CaseForm's get-or-create-by-name, easily
    was) attached to case branches owned by different identities. For each
    existing tag: give it to the owner of its first referencing branch,
    and for every *other* owner referencing it, clone a same-named tag row
    for that owner and re-point just that owner's branches at the clone.
    """
    TagModel = apps.get_model("orm", "TagModel")
    CaseBranchModel = apps.get_model("orm", "CaseBranchModel")

    for tag in TagModel.objects.all():
        owner_ids = list(
            CaseBranchModel.objects.filter(tags=tag)
            .order_by("owner_id")
            .values_list("owner_id", flat=True)
            .distinct()
        )

        if not owner_ids:
            # Unreferenced -- there is no branch left to infer an owner
            # from, so the row is dead weight.
            tag.delete()
            continue

        tag.owner_id = owner_ids[0]
        tag.save(update_fields=["owner_id"])

        for owner_id in owner_ids[1:]:
            clone, _ = TagModel.objects.get_or_create(
                name=tag.name, owner_id=owner_id
            )
            branches = CaseBranchModel.objects.filter(tags=tag, owner_id=owner_id)
            for branch in branches:
                branch.tags.remove(tag)
                branch.tags.add(clone)


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0012_tagmodel_casebranchmodel_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagmodel",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tags",
                to="orm.identitymodel",
            ),
        ),
        migrations.AlterField(
            model_name="tagmodel",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(split_tags_by_owner, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tagmodel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tags",
                to="orm.identitymodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagmodel",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_tag_per_owner"
            ),
        ),
    ]
