# Generated by Django 6.0.5 on 2026-09-09 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0013_tagmodel_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, default="", max_length=255)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiments",
                        to="orm.agenttrailmodel",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiments",
                        to="orm.casetrailmodel",
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_experiments",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "expect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiments",
                        to="orm.expecttrailmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_experiment",
            },
        ),
    ]
