# Generated by Django 6.1.1 on 2026-09-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0013_case_expects_per_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experimentmodel",
            name="scorer",
        ),
        migrations.RemoveField(
            model_name="experimentmodel",
            name="tags",
        ),
    ]
