# Generated by Django 6.1.1 on 2026-09-22 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0014_agent_instruction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expectbranchmodel",
            options={"ordering": ("id",)},
        ),
    ]
