# Generated by Django 6.1.1 on 2026-09-22 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0015_alter_expectbranchmodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="identitymodel",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="tagmodel",
            options={"ordering": ("name",)},
        ),
    ]
