# Generated by Django 6.0.5 on 2026-09-09 00:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0015_experiment_sharedexperiment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stored", "Stored"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("errored", "Errored"),
                            ("completed", "Completed"),
                        ],
                        default="stored",
                        max_length=255,
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True, related_name="shared_runs", to="orm.identitymodel"
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="orm.experimentmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="orm.sessionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_run",
            },
        ),
    ]
