# Installs the schema pgqueuer needs for its own job queue (the "pgqueuer"
# table and friends). This is the same DDL `pgq install` would apply -- see
# https://github.com/janbjorge/pgqueuer -- generated once from
# `pgqueuer.adapters.persistence.qb.QueryBuilderEnvironment().build_install_query()`
# with the library's defaults and pinned here so it doesn't drift if the
# dependency is upgraded later.
from django.db import migrations

INSTALL_SQL = """
CREATE TYPE pgqueuer_status AS ENUM ('queued', 'picked', 'successful', 'exception', 'canceled', 'deleted', 'failed');
CREATE TABLE pgqueuer (
    id BIGSERIAL PRIMARY KEY,
    priority INT NOT NULL,
    queue_manager_id UUID,
    created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    execute_after TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    status pgqueuer_status NOT NULL,
    entrypoint TEXT NOT NULL,
    dedupe_key TEXT,
    payload BYTEA,
    headers JSONB,
    attempts INT NOT NULL DEFAULT 0
);
CREATE INDEX pgqueuer_priority_id_id1_idx ON pgqueuer (priority ASC, id DESC)
    INCLUDE (id) WHERE status = 'queued';
CREATE INDEX pgqueuer_updated_id_id1_idx ON pgqueuer (updated ASC, id DESC)
    INCLUDE (id) WHERE status = 'picked';
CREATE INDEX pgqueuer_queue_manager_id_idx ON pgqueuer (queue_manager_id)
    WHERE queue_manager_id IS NOT NULL;
CREATE INDEX pgqueuer_ep_prio_id_idx ON pgqueuer (entrypoint, priority DESC, id ASC)
    WHERE status = 'queued';
CREATE INDEX pgqueuer_ep_ea_idx ON pgqueuer (entrypoint, execute_after)
    WHERE status = 'queued';
CREATE UNIQUE INDEX IF NOT EXISTS pgqueuer_unique_dedupe_key ON
    pgqueuer (dedupe_key) WHERE ((status IN ('queued', 'picked') AND dedupe_key IS NOT NULL));

CREATE TABLE pgqueuer_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    job_id BIGINT NOT NULL,
    status pgqueuer_status NOT NULL,
    priority INT NOT NULL,
    entrypoint TEXT NOT NULL,
    traceback JSONB DEFAULT NULL,
    aggregated BOOLEAN DEFAULT FALSE
);
CREATE INDEX pgqueuer_log_not_aggregated ON pgqueuer_log ((1)) WHERE not aggregated;
CREATE INDEX pgqueuer_log_created ON pgqueuer_log (created);
CREATE INDEX pgqueuer_log_status ON pgqueuer_log (status);
CREATE INDEX pgqueuer_log_job_id_status ON pgqueuer_log (job_id, created DESC);

CREATE TABLE pgqueuer_statistics (
    id BIGSERIAL PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT DATE_TRUNC('sec', NOW() at time zone 'UTC'),
    count BIGINT NOT NULL,
    priority INT NOT NULL,
    status pgqueuer_status NOT NULL,
    entrypoint TEXT NOT NULL
);
CREATE UNIQUE INDEX pgqueuer_statistics_unique_count ON pgqueuer_statistics (
    priority,
    DATE_TRUNC('sec', created at time zone 'UTC'),
    status,
    entrypoint
);

CREATE TABLE pgqueuer_schedules (
    id BIGSERIAL PRIMARY KEY,
    expression TEXT NOT NULL, -- Crontab-like schedule definition (e.g., '* * * * *')
    entrypoint TEXT NOT NULL,
    heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    next_run TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    last_run TIMESTAMP WITH TIME ZONE,
    status pgqueuer_status DEFAULT 'queued',
    UNIQUE (expression, entrypoint)
);

CREATE FUNCTION fn_pgqueuer_changed() RETURNS TRIGGER AS $$
DECLARE
    to_emit BOOLEAN := false;
BEGIN
    IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
        to_emit := true;
    ELSIF TG_OP = 'DELETE' THEN
        to_emit := true;
    ELSIF TG_OP = 'INSERT' THEN
        to_emit := true;
    ELSIF TG_OP = 'TRUNCATE' THEN
        to_emit := true;
    END IF;

    IF to_emit THEN
        PERFORM pg_notify(
            'ch_pgqueuer',
            json_build_object(
                'channel', 'ch_pgqueuer',
                'operation', lower(TG_OP),
                'sent_at', NOW(),
                'table', TG_TABLE_NAME,
                'type', 'table_changed_event'
            )::text
        );
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NULL;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_pgqueuer_changed
AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pgqueuer
EXECUTE FUNCTION fn_pgqueuer_changed();
"""

UNINSTALL_SQL = """
DROP TRIGGER    IF EXISTS   tg_pgqueuer_changed ON pgqueuer;
DROP FUNCTION   IF EXISTS   fn_pgqueuer_changed;
DROP TABLE      IF EXISTS   pgqueuer;
DROP TABLE      IF EXISTS   pgqueuer_statistics;
DROP TABLE      IF EXISTS   pgqueuer_schedules;
DROP TABLE      IF EXISTS   pgqueuer_log;
DROP TYPE       IF EXISTS   pgqueuer_status;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0016_runmodel"),
    ]

    operations = [
        migrations.RunSQL(sql=INSTALL_SQL, reverse_sql=UNINSTALL_SQL),
    ]
