# Generated by Django 6.1.1 on 2026-09-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0016_alter_identitymodel_options_alter_tagmodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="runmodel",
            name="output",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="outputtypetrailmodel",
            name="coercion_strategy",
            field=models.CharField(
                choices=[
                    ("prompted", "Prompted"),
                    ("tool", "Tool"),
                    ("native", "Native"),
                    ("auto", "Auto"),
                ],
                default="native",
                max_length=255,
            ),
        ),
    ]
