# Generated by Django 6.1.1 on 2026-09-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0019_remove_expecttrailmodel_output_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[],
            options={
                "verbose_name": "Run",
                "verbose_name_plural": "Runs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.runmodel",),
        ),
        migrations.CreateModel(
            name="SharedRun",
            fields=[],
            options={
                "verbose_name": "Shared Run",
                "verbose_name_plural": "Shared Runs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orm.run",),
        ),
    ]
