# Generated by Django 6.1.1 on 2026-09-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0020_run_sharedrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScorerTrailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "agents_scorer",
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="expecttrailmodel",
            name="scorer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expects",
                to="orm.scorertrailmodel",
            ),
        ),
        migrations.AlterField(
            model_name="experimentmodel",
            name="scorer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="experiments",
                to="orm.scorertrailmodel",
            ),
        ),
        migrations.CreateModel(
            name="ScorerBranchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_%(class)s",
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm.identitymodel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="orm.scorertrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "agents_scorer_branch",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "name", "-timestamp"],
                        name="agents_scor_owner_i_930e23_idx",
                    )
                ],
            },
        ),
    ]
