# Generated by Django 6.1.1 on 2026-09-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0021_scorertrailmodel_alter_expecttrailmodel_scorer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmodel",
            name="context",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("repl", "REPL"),
                    ("experiment", "Experiment"),
                ],
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
