# Generated by Django 6.1.1 on 2026-09-10 17:29

import chatddx.repo.base
import chatddx.repo.proxies
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0022_sessionmodel_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedCase",
            fields=[],
            options={
                "verbose_name": "Shared Case",
                "verbose_name_plural": "Shared Cases",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                chatddx.repo.base.BranchProxy,
                "orm.casebranchmodel",
                chatddx.repo.proxies.Shared,
            ),
        ),
    ]
