# Generated by Django 6.1.1 on 2026-09-27 23:21

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import chatddx.repo.families.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_identity_by_name_alone"),
        ("repo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("context", models.CharField(max_length=16)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_conversations",
                        to="core.identitymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.identitymodel",
                    ),
                ),
            ],
            options={
                "db_table": "history_conversation",
            },
        ),
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_uuid", models.UUIDField(db_index=True)),
                ("role", models.CharField(max_length=16)),
                ("kind", models.CharField(max_length=16)),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="history.conversationmodel",
                    ),
                ),
            ],
            options={
                "db_table": "history_message",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="RunModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=16)),
                (
                    "client_rev",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("client_packages", models.JSONField(blank=True, default=dict)),
                ("started", models.DateTimeField(blank=True, default=None, null=True)),
                ("finished", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "requests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "responses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "answer",
                    chatddx.repo.families.django.OrderedJSONField(
                        blank=True, default=None, null=True
                    ),
                ),
                ("valid", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "finish_reason",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("error", models.TextField(blank=True, default=None, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.clienttrailmodel",
                    ),
                ),
                (
                    "coercion_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.coercionbranchmodel",
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True, related_name="shared_runs", to="core.identitymodel"
                    ),
                ),
                (
                    "configuration_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.configurationbranchmodel",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="history.conversationmodel",
                    ),
                ),
                (
                    "instruction_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.instructionbranchmodel",
                    ),
                ),
                (
                    "llm_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.llmbranchmodel",
                    ),
                ),
                (
                    "output_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.outputbranchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.identitymodel",
                    ),
                ),
                (
                    "reasoning_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.reasoningbranchmodel",
                    ),
                ),
                (
                    "sampling_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.samplingbranchmodel",
                    ),
                ),
                (
                    "stack_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.stackbranchmodel",
                    ),
                ),
                (
                    "toolset_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="repo.toolsetbranchmodel",
                    ),
                ),
            ],
            options={
                "db_table": "history_run",
            },
        ),
        migrations.CreateModel(
            name="RunToolModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blob", models.CharField(max_length=64)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.runmodel",
                    ),
                ),
                (
                    "tool_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="repo.toolbranchmodel",
                    ),
                ),
            ],
            options={
                "db_table": "history_run_tool",
            },
        ),
        migrations.AddField(
            model_name="runmodel",
            name="tool_branches",
            field=models.ManyToManyField(
                blank=True,
                related_name="runs",
                through="history.RunToolModel",
                to="repo.toolbranchmodel",
            ),
        ),
        migrations.CreateModel(
            name="ScoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scorer_name", models.CharField(max_length=255)),
                ("target", models.TextField(blank=True, default=None, null=True)),
                ("blob", models.CharField(max_length=64)),
                ("value", models.FloatField(blank=True, default=None, null=True)),
                ("answer", models.TextField(blank=True, default=None, null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "case_branch",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="repo.casebranchmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.identitymodel",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="history.runmodel",
                    ),
                ),
                (
                    "scorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="repo.scorertrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "history_score",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="TrialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("seed", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="repo.casetrailmodel",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="repo.configurationtrailmodel",
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trials",
                        to="repo.stacktrailmodel",
                    ),
                ),
            ],
            options={
                "db_table": "history_trial",
            },
        ),
        migrations.AddField(
            model_name="runmodel",
            name="trial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="history.trialmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="trialmodel",
            constraint=models.UniqueConstraint(
                fields=("configuration", "stack", "case", "seed"),
                name="one_trial_per_cell_case_and_seed",
                nulls_distinct=False,
            ),
        ),
    ]
