# Generated by Django 6.1.1 on 2026-09-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
        ("repo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RunToolBranchModel",
            new_name="RunToolModel",
        ),
        migrations.AlterModelTable(
            name="runtoolmodel",
            table="history_run_tool",
        ),
    ]
