# Generated by Django 6.1.1 on 2026-09-27 19:26

import chatddx.core.django_fields
import chatddx.repo.entities.tool.django
import chatddx.repo.families.django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vignette', models.TextField()),
            ],
            options={
                'db_table': 'repo_case_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('build', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repo_client_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoercionTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(max_length=16)),
                ('schema_prompt', models.TextField(blank=True, null=True)),
                ('tool_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repo_coercion_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructionTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('system', models.TextField(blank=True)),
                ('user', models.TextField()),
                ('variables', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'repo_instruction_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.TextField()),
            ],
            options={
                'db_table': 'repo_llm_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine_id', models.UUIDField()),
            ],
            options={
                'db_table': 'repo_machine_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OsTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('toplevel', models.TextField()),
            ],
            options={
                'db_table': 'repo_os_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer_schema', chatddx.repo.families.django.OrderedJSONField(blank=True, null=True)),
                ('guidance', models.TextField(blank=True, null=True)),
                ('views', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'repo_output_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasoningTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('effort', models.CharField(max_length=16)),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repo_reasoning_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('defaults', models.CharField(max_length=32)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('top_k', models.IntegerField(blank=True, null=True)),
                ('max_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('presence_penalty', models.FloatField(blank=True, null=True)),
                ('frequency_penalty', models.FloatField(blank=True, null=True)),
                ('stop', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repo_sampling_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScorerTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('function', models.CharField(max_length=255)),
                ('view', models.CharField(max_length=32)),
                ('target_kind', models.CharField(blank=True, max_length=32, null=True)),
                ('args', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'repo_scorer_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServingTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('engine', models.TextField()),
                ('args', models.JSONField(blank=True, default=dict)),
                ('env', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'repo_serving_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolsetTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('guidance', models.TextField(blank=True, null=True)),
                ('tools', chatddx.core.django_fields.RelatedArrayField(associated_model=chatddx.repo.entities.tool.django.ToolTrailModel, base_field=models.IntegerField(), default=list)),
            ],
            options={
                'db_table': 'repo_toolset_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('parameters', chatddx.repo.families.django.OrderedJSONField()),
            ],
            options={
                'db_table': 'repo_tool_trail',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.casetrailmodel')),
            ],
            options={
                'db_table': 'repo_case_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.clienttrailmodel')),
            ],
            options={
                'db_table': 'repo_client_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoercionBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.coerciontrailmodel')),
            ],
            options={
                'db_table': 'repo_coercion_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigurationBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
            ],
            options={
                'db_table': 'repo_configuration_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigurationTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coercion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='repo.coerciontrailmodel')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='repo.instructiontrailmodel')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='repo.outputtrailmodel')),
                ('reasoning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='repo.reasoningtrailmodel')),
                ('sampling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='repo.samplingtrailmodel')),
                ('toolset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='repo.toolsettrailmodel')),
            ],
            options={
                'db_table': 'repo_configuration_trail',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='configurationbranchmodel',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.configurationtrailmodel'),
        ),
        migrations.CreateModel(
            name='InstructionBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.instructiontrailmodel')),
            ],
            options={
                'db_table': 'repo_instruction_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.llmtrailmodel')),
            ],
            options={
                'db_table': 'repo_llm_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.machinetrailmodel')),
            ],
            options={
                'db_table': 'repo_machine_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OsBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.ostrailmodel')),
            ],
            options={
                'db_table': 'repo_os_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.outputtrailmodel')),
            ],
            options={
                'db_table': 'repo_output_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasoningBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.reasoningtrailmodel')),
            ],
            options={
                'db_table': 'repo_reasoning_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.samplingtrailmodel')),
            ],
            options={
                'db_table': 'repo_sampling_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScorerBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.scorertrailmodel')),
            ],
            options={
                'db_table': 'repo_scorer_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServingBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.servingtrailmodel')),
            ],
            options={
                'db_table': 'repo_serving_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
            ],
            options={
                'db_table': 'repo_stack_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackTrailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('host_os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosted_stacks', to='repo.ostrailmodel')),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stacks', to='repo.llmtrailmodel')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stacks', to='repo.machinetrailmodel')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stacks', to='repo.ostrailmodel')),
                ('serving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stacks', to='repo.servingtrailmodel')),
            ],
            options={
                'db_table': 'repo_stack_trail',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stackbranchmodel',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.stacktrailmodel'),
        ),
        migrations.CreateModel(
            name='ToolBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.tooltrailmodel')),
            ],
            options={
                'db_table': 'repo_tool_branch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolsetBranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_%(class)s', to='core.identitymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_%(class)s', to='core.identitymodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_%(class)s', to='core.tagmodel')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='repo.toolsettrailmodel')),
            ],
            options={
                'db_table': 'repo_toolset_branch',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='casebranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_case_b_owner_i_a74684_idx'),
        ),
        migrations.AddIndex(
            model_name='clientbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_client_owner_i_94f1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='coercionbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_coerci_owner_i_f2b6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_config_owner_i_ab7f41_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_instru_owner_i_7d32a6_idx'),
        ),
        migrations.AddIndex(
            model_name='llmbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_llm_br_owner_i_354ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='machinebranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_machin_owner_i_e9cbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='osbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_os_bra_owner_i_03f71b_idx'),
        ),
        migrations.AddIndex(
            model_name='outputbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_output_owner_i_44c681_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoningbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_reason_owner_i_a8c343_idx'),
        ),
        migrations.AddIndex(
            model_name='samplingbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_sampli_owner_i_124612_idx'),
        ),
        migrations.AddIndex(
            model_name='scorerbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_scorer_owner_i_8dab84_idx'),
        ),
        migrations.AddIndex(
            model_name='servingbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_servin_owner_i_7a67cc_idx'),
        ),
        migrations.AddIndex(
            model_name='stackbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_stack__owner_i_081877_idx'),
        ),
        migrations.AddIndex(
            model_name='toolsetbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_toolse_owner_i_8cc74a_idx'),
        ),
        migrations.AddIndex(
            model_name='toolbranchmodel',
            index=models.Index(fields=['owner', 'name', '-timestamp'], name='repo_tool_b_owner_i_0f7b76_idx'),
        ),
    ]
